/*******************************************************************************
 * Copyright (c) 2000, 2021 IBM Corporation and others.
 *
 * This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * This is an implementation of an early-draft specification developed under the Java
 * Community Process (JCP) and is made available for testing and evaluation purposes
 * only. The code is not compatible with any specification of the JCP.
 *
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
package org.eclipse.jdt.internal.compiler.parser;

/*An interface that contains static declarations for some basic information
 about the parser such as the number of rules in the grammar, the starting state, etc...*/
public interface ParserBasicInformation {

	public final static int
	// BEGIN_AUTOGENERATED_REGION

					ERROR_SYMBOL = 153,
					MAX_NAME_LENGTH = 53,
					NUM_STATES = 1479,

					NT_OFFSET = 153,
					SCOPE_UBOUND = 403,
					SCOPE_SIZE = 404,
					LA_STATE_OFFSET = 21012,
					MAX_LA = 1,
					NUM_RULES = 1101,
					NUM_TERMINALS = 153,
					NUM_NON_TERMINALS = 501,
					NUM_SYMBOLS = 654,
					START_STATE = 1701,
					EOFT_SYMBOL = 69,
					EOLT_SYMBOL = 69,
					ACCEPT_ACTION = 21011,
					ERROR_ACTION = 21012;
}
